blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'
urlpatterns = [
    path(r'', views.loginPage, name='login'),
    path('login/',views.loginPage, name='login'),
    path('home/',views.home, name='home'),
    path('logout/',views.logoutUser, name='logout'),
    path('register/',views.registerUser,name='register'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/inbox',views.inbox, name='inbox'),
    path('post/trendingTopics', views.trendingTopics, name='trendingTopics'),
    path('post/profile',views.profile, name='profile'),
    path('post/<int:pk>/makeComment',views.makeComment, name='makeComment'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import TemplateView


urlpatterns = [
    path(r'', include('blog.urls')),
    path('admin/', admin.site.urls),
    #path('',TemplateView.as_view(template_name='index.html')),
]

blog/models.py
from django.db import models
from django.utils import  timezone
from django.contrib.auth.models import User


class CustomUser(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_name = models.CharField(max_length = 40)
    biography = models.CharField(max_length = 200)
    profile_img = models.CharField(max_length=200)
    friends = models.ManyToManyField('CustomUser')


    def __str__(self):
        return self.user_name

class UserFriends(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.CharField(max_length = 200)
    img_path = models.CharField(max_length = 200)
    created_date = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField()

    # methods
    def publish(self):
        self.created_date = timezone.now()
        self.save()

    def getUserInfo(self,user):
        userInfo = CustomUser.objects.get(user=user)
        return userInfo

    def getPost(self, post):
        comments = Comment.getComments(Comment,post=post)
        user = Post.getUserInfo(Post,post.user)
        return {'post':post, 'comments':comments, 'user':user}

    def __str__(self):
        return self.description



class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.CASCADE)
    users_who_commented = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    liked = models.IntegerField()

    def getCommentAuthor(self,author):
        user = CustomUser.objects.get(user=author)
        return user

    def getComments(self,post):
        comments = Comment.objects.filter(post=post)
        comments = [ {'comment':comment,'user':Comment.getCommentAuthor(Comment,comment.users_who_commented)} for comment in comments ]
        return comments


class Story(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    img_path = models.CharField(max_length=200)
    creation_date = models.DateTimeField(default=timezone.now)

    def getUserName(self,story):
        user = CustomUser.objects.get(user=story.user)
        return {'story':story, 'user':user}

blog/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('description','img_path','created_date')


class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import Post, Comment, CustomUser, Story
from .forms import PostForm, CreateUserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
# flash messages
from django.contrib import messages



def registerUser(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            customUser = CustomUser()
            customUser.user = User.objects.get(username=user)
            customUser.user_name = user
            customUser.biography = ""
            customUser.profile_img = "/img/profiles/11.jpg"
            customUser.save()
            messages.success(request,'Account created for '+user)
            return redirect('blog:login')

    context = {'form': form}
    return render(request,'blog/register.html',context=context)


def loginPage(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)
        
        if user is not None:
            login(request,user)
            return redirect('blog:home')
        else:
            messages.info(request,'Username OR password is incorrect')

    context = {}
    return render(request, 'blog/login.html',context=context)


def logoutUser(request):
    logout(request)
    return redirect('blog:login')



def home(request):
    user = CustomUser.objects.get(user=request.user.id)
    users = CustomUser.objects.all() # this are supossed to be the friends
    posts = Post.objects.all()
    posts = [ Post.getPost(Post,post) for post in posts ]
    storys = Story.objects.all() # this are the storys of every friend
    storys = [ Story.getUserName(Story,story) for story in storys ]
    return render(
        request, 
        'blog/post_list.html', 
        {
            'posts': posts, 
            'users': users, 
            'user': user, 
            'storys':storys,
        }
    ) 


def post_detail(request, pk):
    user = CustomUser.objects.get(user=request.user.id)
    posts = Post.objects.filter(id=pk).order_by('created_date')  #get_object_or_404(request, pk=pk)
    return render(request, 'blog/post_detail.html', {'posts': posts,'user':user})


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    
    return render(request,'blog/post_edit.html', {'form': form})


def post_edit(request, pk):
    user = CustomUser.objects.get(user=request.user.id)
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail',pk=pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {'form': form, 'user':user})

def inbox(request):
    user = CustomUser.objects.get(user=request.user.id)
    users = CustomUser.objects.all() # these are supossed to be friends
    return render(request,'blog/inbox.html',{'user':user,'users':users})

def trendingTopics(request):
    user = CustomUser.objects.get(user=request.user.id)
    posts = Post.objects.all()
    return render(request,'blog/trendingTopics.html',{'user':user, 'posts': posts})


def profile(request):
    user = CustomUser.objects.get(user=request.user.id)
    posts = Post.objects.filter(user=request.user.id)
    storys = Story.objects.filter(user=request.user.id)
    postsCount = len(posts)
    return render(
        request,
        'blog/profile.html',
        {
            'user':user, 
            'posts': posts, 
            'storys':storys,
            'postsCount': postsCount
        })


def makeComment(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(id=pk)
        comment = Comment()
        comment.post = post
        comment.users_who_commented = request.user
        comment.content = request.POST.get('userComment')
        comment.liked = 0
        if comment.save():
            return redirect('blog:home')
        
    return redirect('blog:home')

blog/templates/blog/base.html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>My site</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" href="{% static 'css/modals.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}" />
        <link rel="icon" href="{% static 'img/igLogo' %}" type="image/jpeg">
    </head>
    <body>
      
      <div class="sticky-top page-header container-fluid">
        <div class="d-flex flex-row bd-highlight">
          <div class="title navbar-brand">
            <img class="logo-image" src="{% static 'img/instagram.png' %}">
          </div>
          <div class="col col-sm" > 
            <form class="search-top-form form-inline">
              <div class="input-group input-group-sm mb-3" >
                <input class="form-control search-input" type="search" placeholder="  Search" aria-label="Search" >
              </div>
            </form>
          </div>
          <div class="top-menu-list col nav" >
            <ul class="list-group list-group-horizontal-sm">
              <li class="icon-list list-group-item"><a href="{% url 'blog:home' %}"><i class="fas fa-home fa-lg"></i></a></li>
              <li class="icon-list list-group-item"><a href="{% url 'blog:inbox' %}"><i class="far fa-paper-plane fa-lg"></i></a></li>
              <li class="icon-list list-group-item"><a href="{% url 'blog:trendingTopics' %}"><i class='far fa-compass fa-lg'></i></a></li>
              <li class="icon-list list-group-item nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="far fa-heart fa-lg"></i></a> 
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#"> some stuf</a>
                  <a class="dropdown-item" href="#"> ascim</a>
                  <a class="dropdown-item" href="#"> ojrfe </a>
                  <a class="dropdown-item" href="#"> regewtuf</a>...
                </div>
              </li>
              <li class="icon-list list-group-item nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img class="top-user-img rounded-circle" src="{% static user.profile_img %}" ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'blog:profile' %}"><i class="far fa-user-circle"></i> Profile</a>
                  <a class="dropdown-item" href="#"><i class="far fa-bookmark"></i> Saved</a>
                  <a class="dropdown-item" href="#"><i class="fas fa-cog"></i>                     
                    Settings
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'blog:logout' %}"><i class="fas fa-sign-out-alt"></i><b> Logout</b></a>
                </div>
              </li> 
            </ul>
          </div>
        </div>
      </div>

    

      {% block content %}{% endblock content %}

    </body>
</html>

blog/templates/blog/login.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}



<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="login">
            <div class="cont-form">
                <div class="title-reg">
                    <img class="instagram-title" src="{% static 'img/instagram.png' %}">
                </div>
                <div class="center-block form-login">
                    <form id="id_form_login" method="POST" class="register">
                        {% csrf_token %}
                        <div class="form-group aling-items-center">
                            <div class="fields col">
                                <input type="text" id="username" name="username" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group aling-items-center">
                            <div class="fields col">
                                <input type="password" id="password" name="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-row aling-items-center">
                            <div class="btn-register container">
                                <button id="id_btn_login" type="submit" class="btn btn-primary btn-sm btn-block">Log In</button>
                            </div>
                            <div class="footer-register mx-auto">
                                <p>You don't have an account? <a href="{% url 'blog:register' %}">Sign up</a></p>
                            </div>
                        </div>
                    </form>
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                            {{message}}
                        </div>
                    {% endfor %}  
                </div>
                <div class="divider"></div>
                <div class="forgot-password mx-auto">
                    <p><a href="#">Forgot password?</a></p>
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="post">
        {% for post in posts  %}
            <div class="date">
                {{ post.created_date }}
            </div>
            <a class="btn btn-default" href="{% url 'blog:post_edit' post.id %}">Editar</a>
            <h1>{{ post.user_name }}</h1>
            <p>{{ post.description|linebreaks }}</p>
        {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}
{% bootstrap_button %}

{% block content %}
    <h1>New Post Form</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}    
    </form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<div class="container">

    <!-- Row that wraps everything -->
    <div class="row justify-content-center">

        <!-- Storys and Feed -->
        <div class="col-8 col-sm-8 col-xs-9 col-md-6 col-lg-8">
            <div class="card-deck">
                <div class="card content border-0">
                    <div class="card-post">
                        <div class="storys-list container-fluid">
                            <ul class="nav">
                                <li class="nav-item">
                                    <div class="row justify-content-center">
                                        <div class="col">
                                            <img class="story rounded-circle" src="{% static user.profile_img %}">
                                        </div>
                                    </div>    
                                    <div class="row justify-content-center">
                                        <div class="col">
                                            <small class="text-lowercase">{{ user.user_name }}</small>
                                        </div>
                                    </div>
                                </li>
                                {% for story in storys %}
                                <li class="nav-item">
                                    <div class="row justify-content-center">
                                        <div class="col">
                                            <img class="story rounded-circle" src="{% static story.story.img_path %}">
                                        </div>
                                    </div> 
                                    <div class="row justify-content-center">
                                        <div class="col text-truncate" style="width: 56px;">
                                            <small>{{ story.user.user_name }}</small>
                                        </div>
                                    </div>
                                </li>  
                                {% endfor %}
                            </ul>
                        </div> 
                    </div>
                    {% for post in posts %}
                    <div class="card-post">
                        <div class="card-header">
                            <img class="story-header" src="{% static post.user.profile_img %}">
                            <h5 class="user-name"><a class="text-dark text-decoration-none text-lowercase font-weight-bold" href="{% url 'blog:post_detail' post.post.id %}">{{ post.user.user_name }}</a></h5>
                        </div>
                        <img src="{% static post.post.img_path %}" class="card-img-top" alt="...">
                        <div class="card-body post-card">
                            <div class="icons container-fluid">
                                <div class="container menu-items-list row">
                                    <div class="col left-icons" >
                                        <ul class="icons-post-list list-group list-group-horizontal">
                                            <li class="list-group-item"><i class="icons-post-menu far fa-heart"></i></li>
                                            <li class="list-group-item"><i class="icons-post-menu far fa-comment"></i></li>
                                            <li class="list-group-item"><i class="icons-post-menu far fa-paper-plane"></i></li>
                                        </ul>
                                    </div>
                                    <div class="col right-icons" >
                                        <i class="icons-post-menu far fa-bookmark"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="mt-n3 p-0 container-fluid">
                                <div class="post-description-header">
                                    <div class="user-post-comment">
                                        <b class="text-lowercase">{{ post.user.user_name }}</b>            
                                    </div>
                                    <p>{{ post.post.description|linebreaks }}</p>
                                </div>
                                {% for comment in post.comments %}
                                <div class="comments-card">
                                    <div class="comment-img">
                                        <!-- uncomment the line below if you want to have the picture of the guy who commented -->
                                        <!--
                                        <img class="user-profile-pic" src="{% static post.user.profile_img %}">
                                        -->
                                        <b>{{ comment.user.user_name }}</b>
                                    </div>
                                    <div class="comment-content">
                                        <p>{{ comment.comment.content }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <form class="form inline-form" id="commentForm" method="POST" action="{% url 'blog:makeComment' post.post.id %}">{% csrf_token %}
                        <div class="add-comment card-footer bg-transparent input-group">
                            <input id="userComment" name="userComment" class="comment-input form-control" type="text" name="comments" placeholder="Add a comment...">
                            <div class="comment-btn input-group-append">
                                <button type="submit" class="btn btn-sm btn-link mb-2"><b>Post</b></button>
                            </div>                  
                        </div>
                        </form>
                    </div>
                    {% endfor %}  
    
    
                </div>
            </div>
        </div> 
    
        <!-- Sidebar Main View -->
        <div class="col-4 col-sm col-xs col-md-6 col-lg-4">
            <div class="settings-column px-sm-5">
              <div class="side-panel card-body">
                <div class="">
                  <img class="user-profile-pic" src="{% static user.profile_img %}" >
                  <h5 class="card-title user-title">
                    <b>{{user.user_name}}</b>
                    <p class="sub-title-user"><small class="text-muted">{{user.user}}</small></p>  
                  </h5>
                </div>
                <div class="suggestions-title" >
                  <p class="card-text text-muted">
                    <b style="font-size: medium;">Suggestions For You</b>
                    <a href="{% url 'blog:post_new' %}" class="see-all text-decoration-none text-dark" ><strong>Add post</strong></a>
                  </p>
                </div>
                <div class="sugestion-list">
                  <table class="table table-sm" style="border: none;">
                    <tbody>
                    {% for user in users %}
                      <tr>
                        <td colspan="1" class="img-table">
                          <img src="{% static user.profile_img %}" class="user-profile-pic" >
                        </td>
                        <td colspan="2">
                          <div class="suggestion-user-name">
                            <h5 class="card-title user-title">
                              <b>{{user.user_name}}</b>
                              <p class="sub-title-user"><small class="text-muted">{{user.user}}</small></p>  
                            </h5>
                          </div>
                        </td>
                        <td class="link-table" colspan="1">
                          <small><a href="{% url 'blog:home' %}" class="link-follow text-decoration-none" ><b>Follow</b></a></small>
                        </td>
                      </tr>
                    {% endfor %}
                   </tbody>
                  </table>
                  <p class="font-weight-bold text-secondary text-center">
                    <small>
                      <i class="fas fa-info-circle"></i> 
                      This site is not responsive yet! Be patient please. I'm working on it.
                    </small>
                  </p>
                </div>
              </div>
            </div>
        </div>

    </div>

</div> <!-- end of the container -->
   

{% endblock content %}

blog/templates/blog/profile.html
{% extends "blog/base.html" %}
{% load static %}


{% block content %}
    <div class="container py-md-5" >

        <div class="row justify-content-start">
            <div class="container-fluid media">
                <div class="container w-25 ml-5">
                    <img class="profile-img-big rounded-circle" src="{% static user.profile_img %}">
                </div>
                <div class="media-body">
                    <h3 class="mt-0 p-0 mb-4">{{user.user}}
                        <button type="button" class="btn btn-sm btn-light border font-weight-bold ml-5"> Edit profile</button>
                        <a class="text-dark ml-3" href="#" data-toggle="modal" data-target="#profileSettings"><i class="fas fa-cog"></i></a>
                    </h3>
                    <div class="container-fluid p-0">
                        <div class="list-group">
                            <ul class="list-group list-group-horizontal-sm">
                                <li class="list-group-item border-0 ml-n3" style="background-color: rgba(var(--b3f,250,250,250),1);"><b>{{postsCount}}</b> posts</li>
                                <li class="list-group-item border-0" style="background-color: rgba(var(--b3f,250,250,250),1);" ><b>{{user}}</b> followers</li>
                                <li class="list-group-item border-0" style="background-color: rgba(var(--b3f,250,250,250),1);" ><b>98</b> following</li>
                            </ul>
                        </div>
                        <h5 class="font-weight-bold p-0 ml-1" >{{user.user_name}}</h5>
                        <p class="ml-1" >{{user.biography}}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-start py-md-4" >
            <div class="container-fluid w-100">
                <div class="card border-0" style="background-color: rgba(var(--b3f,250,250,250),1);" >
                    <div class="card-body">
                        <div class="nav ml-3">
                            {% for story in storys %}
                            <li class="nav-item px-sm-3 px-md-4">
                                <div class="row justify-content-center">
                                    <div class="col">
                                        <img class="profile-storys rounded-circle" src="{% static story.img_path %}" >
                                    </div>
                                </div>
                                <div class="row justify-content-center">
                                    <div class="col text-truncate" style="width: 56px;">
                                        <small>{{story.creation_date}}</small>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="border-top py-2 row justify-content-center align-items-center">
            <ul class="px-3 mt-n2 list-group list-group-horizontal">
                <li class="list-group-item border-0 text-uppercase text-muted"><small><i class="fas fa-th"></i> posts</small></li>
                <li class="list-group-item border-0 text-uppercase text-muted"><small><i class="fas fa-tv"></i> igtv</small></li>
                <li class="list-group-item border-0 text-uppercase text-muted"><small><i class="far fa-bookmark "></i> saved</small></li>
                <li class="list-group-item border-0 text-uppercase text-muted"><small><i class="far fa-address-book"></i> tagged</small></li>
            </ul>
        </div>

        <div class="row justify-content-start align-items-start">
            {% for post in posts %}
                <div class="col px-3" style="max-width: min-content;">
                    <img class="card-img-top story-card-feed-img" src="{% static post.img_path %}" >
                </div>
            {% endfor %}
        </div>


        <!-- Modal Profile Settings -->
        <div class="modal fade" id="profileSettings" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modalSettings borders-top borders-bot">
                <div class="modal-content borders-top borders-bot">
                    <div class="list-group borders-top borders-bot">
                        <a href="#" class="list-group-item list-group-item-action text-center borders-top">Change Password</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Nametag</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Apps and Websites</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Notifications</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Privacy and Security</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Login Activity</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Emails from Instagram</a>
                        <a href="#" class="list-group-item list-group-item-action text-center">Report a Problem</a>
                        <a href="{% url 'blog:logout' %}" class="list-group-item list-group-item-action text-center">Log Out</a>
                        <a href="#" class="list-group-item list-group-item-action text-center borders-bot" data-dismiss="modal">Cancel</a>
                    </div>
                </div>
            </div>
        </div>


    </div>



{% endblock content %}

blog/templates/blog/trendingTopics.html
{% extends "blog/base.html" %}
{% load static %}


{% block content %}
    <div class="container py-sm-4">
        <div class="row justify-content-center align-items-start">
            {% for post in posts %}
            <div class="col-sm px-sm-2 py-sm-1">
                <div class="card border-0">
                    <img class="card-img-top story-card-feed-img" src="{% static post.img_path %}" >
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="footer container-fluid border-top py-sm-3">
        <ul class="nav justify-content-center">
            <li class="nav-item"><a class="nav-link text-dark font-weight-bold" href="#">Contact</a></li>
            <li class="nav-item"><a class="nav-link text-dark font-weight-bold" href="#">About me</a></li>
            <li class="nav-item"><a class="nav-link text-dark font-weight-bold" href="#">Github repo</a></li>
            <li class="nav-item"><a class="nav-link text-dark font-weight-bold" href="#">My Instagram</a></li>
        </ul>
    </div>
{% endblock content %}